[gcp_service_account]
type = "service_account"
project_id = "weighty-psyche-484109-v7"
private_key_id = "18cf591b0bce1ca7c144be2e1932ffdea644c166"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvt3Gp3AIvk5c+\nxZ/D2lwLDxbC4Z8dzVPyGGQczo9bwsdkd921lK6nsryGBnfqikof2qEJwfRQzAYx\n8FK9aQmBtkHjnLK2RPvy61XyBCgU9HZnjxmMWBV6L5e01j27D3pYwWalCtyJ8vDt\nLQEJuT8Q9q9Wy8/AxCHhzh9z1gjqiSkqs24hb7WFv1Wsig9bBwLjXQz7IVOpeYGa\nwTFESpz7QiJBttB2PoZJbofYg14Czn57CFpq3g04XUgUleLtIbgcNeu91FYEUt/Z\nAHM/e+FNRJytJ7WbdFn4mOescgC+Re4quJ+Pdn6CyJ9l1sUPr2frEHf2ux9416fH\nQDIYeL9HAgMBAAECggEAFM8Djdr5A0tWIN/kYJwuRD0ANAnl/vB+3W+YA3VOss4p\nMLOlNMiruj5HZxPDBapkxsrsQSyP0zWmEinkknuq3YqI2PyIiV83+vd1kRh+6qRc\nlTz0CJOxz2ttasPoQYu+sF4O2sKjhU6Yy22F7vHaDxc3gm7WZnyTipsPTHdvTN7J\nHkggk9L1T3RYIEp2maCntJhkYRXeVyvTjI4Y/e1Kf4VlUhArieSYyTWhDO1NjChN\n2CRsAJtpIKEObdnjJ6AxGUmvwSCH4qSHMJcwbkOUCp036IitmyL6S2nGovYcglYK\nLmQW1Ln+C6ibLoxEdjeFLnjIsk/eUa12iZYRneMpiQKBgQDVLM6S+0ohOoB6F1kF\ncxTPdaNFoCDz6gyyRalsT8d02XYlii3awUuFmYyhbuVdID+LbGeeMYHGYyUelPPQ\nx9I0ZZPelpSnmfebmhUwxrhtTMJme2wjY9dF8HZ23dG6cw2t0pkz7QmCQXVLk4E1\ne9dfTxVNAjC2heoQyLpV6HkAiwKBgQDTBDgVPOwMWOm0AyVEOKcuVzGER8NFW6vr\nlp0UFh17S2UcXilIO/y2A69Ks/Ro33Zw8qW+iDcLfaMQ5PymEYp39Gv8oj33NWa3\n0qX04AHzUca0iWN+0/IAZH3PBa/k5/LMyDLGjGWz/t8PG5zw5s2H92KJ4ljYUqBD\nzabF25i3tQKBgA1eZ/4TwExhLNl7SVvsIav5BqpBJo/lZ7JuZ/eg8TNEyAIGrmV/\npcrVHFqrZ7r1YMbPn5fuJuNYKGXIlZnMTkR28lUNQHlaUIrzmMycScig/bgLmXaG\ntmNudx9xPcvhl0QFZxI4lVYT4NVChOHjyFfzz7QqpP9tWoZ+8CCfGaeNAoGAKbwx\n43FzNlX3kxT0L/QMjMvODV2sL3GcJTJayvg8yH/29Y9iFtlWeCFucBX7hyp7YId9\nZJvIV0t4DwVbOvVJL8R1/zePje9P65eMH0yW1iscY+SwewssWAuIHoP/cAS4LuyB\nrmdiTiFguLo7ZiIgEH5LTP4pmE9vRznLfGKcZ+kCgYEApW3NdJKmVuGMbLsp8vMU\nBY6e/5mK0VcVaZSQDSN4ceDRYAammiZgVpzfnSNCZB/JH6wYJSyiHrpqqBTlL7xv\niu/Ehs/8gvldghUFVK8vHv+5kPDAXUasZ5mEtbvYBh6YoN1l4b/Qb6jrlMD282vO\nJWYhX5E7y6o4jGchQkYM+78=\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-robot@weighty-psyche-484109-v7.iam.gserviceaccount.com"
client_id = "109996165698656207321"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-robot%40weighty-psyche-484109-v7.iam.gserviceaccount.com"

# 予約フォームで予約を保存するスプレッドシートのID（任意）
# reservation_sheet_id = "ここにスプレッドシートID"

# 控えメールをサーバーから送る場合（任意）。フォームでメールアドレスを入力した人に送信
# [smtp]
# host = "smtp.gmail.com"
# port = 587
# user = "your@gmail.com"
# password = "アプリパスワード"
# from_addr = "your@gmail.com"

[branches]
# ここの "test" の右側に、スプレッドシートのIDを貼り付けてくれ
test = "1c_S_94JTMsBJocFrw2Ri46k9K24Yizv2idYJ39Xj9Ko"